name: GitHub Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install and run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: "--no-color -q"

    - name: Create Package
      uses: BigWigsMods/packager@v2
      env:
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
